# 供 ESM_Fold_hydra.py 使用
# === 统一从环境变量拿关键标量 ===
iteration_num:  ${oc.env:ITER,0}
label: ${oc.env:LABEL,3.1.1.1}
run_dir: ${oc.env:RUN_DIR}

esm:
  model_dir: "/root/zymGFN/esm_fold"
  device: null
  # 内存优化设置
  max_sequence_length: 500  # 最大序列长度，超过则跳过
  batch_size: 1  # 批处理大小
  use_mixed_precision: true  # 使用混合精度
  clear_cache_frequency: 5  # 每处理多少个序列清理一次缓存

paths:
  # 全部用绝对路径（或由 run_dir 拼出的“准绝对路径”）
  fasta_path:   "${run_dir}/seq_gen_${label}_iteration${iteration_num}.fasta"
  sequences_dir: "${run_dir}"
  pdb_dir:       "${run_dir}/PDB"

# 既然我们都用绝对路径了，是否 chdir 就无所谓了；为了避免混淆，可显式关掉
hydra:
  job:
    chdir: false
